<?php

namespace eDemy\WikiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    public function findLastModified($namespace = null)
    {
        $qb = $this->createQueryBuilder('c');
        if($namespace == null) {
            $qb->andWhere('c.namespace is null');
        } else {
            $qb->andWhere('c.namespace = :namespace');
            $qb->setParameter('namespace', $namespace);
        }
        $qb->orderBy('c.updated','DESC');
        $qb->setMaxResults(1);
        $query = $qb->getQuery();

        return $query->getSingleResult();
    }
}
